---

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create tower organization
    ansible.tower.tower_organization:
      name: test_org
      description: "test org"
      state: present

